# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1190, 1092)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bbrowse = QtWidgets.QPushButton(self.centralwidget)
        self.bbrowse.setGeometry(QtCore.QRect(1040, 60, 75, 23))
        self.bbrowse.setObjectName("bbrowse")
        self.lbrowse = QtWidgets.QLineEdit(self.centralwidget)
        self.lbrowse.setGeometry(QtCore.QRect(20, 60, 991, 23))
        self.lbrowse.setObjectName("lbrowse")
        self.ldownload = QtWidgets.QLineEdit(self.centralwidget)
        self.ldownload.setGeometry(QtCore.QRect(910, 100, 111, 23))
        self.ldownload.setObjectName("ldownload")
        self.bdownload = QtWidgets.QPushButton(self.centralwidget)
        self.bdownload.setGeometry(QtCore.QRect(1040, 100, 75, 23))
        self.bdownload.setObjectName("bdownload")
        self.lblpicture1 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture1.setGeometry(QtCore.QRect(10, 140, 151, 171))
        self.lblpicture1.setText("")
        self.lblpicture1.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture1.setScaledContents(True)
        self.lblpicture1.setObjectName("lblpicture1")
        self.blogin = QtWidgets.QPushButton(self.centralwidget)
        self.blogin.setGeometry(QtCore.QRect(1040, 20, 75, 23))
        self.blogin.setObjectName("blogin")
        self.lblusername = QtWidgets.QLabel(self.centralwidget)
        self.lblusername.setGeometry(QtCore.QRect(20, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblusername.setFont(font)
        self.lblusername.setObjectName("lblusername")
        self.lblpassword = QtWidgets.QLabel(self.centralwidget)
        self.lblpassword.setGeometry(QtCore.QRect(560, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblpassword.setFont(font)
        self.lblpassword.setObjectName("lblpassword")
        self.lusername = QtWidgets.QLineEdit(self.centralwidget)
        self.lusername.setGeometry(QtCore.QRect(90, 20, 371, 23))
        self.lusername.setObjectName("lusername")
        self.lpassword = QtWidgets.QLineEdit(self.centralwidget)
        self.lpassword.setGeometry(QtCore.QRect(640, 20, 371, 23))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.lpassword.setFont(font)
        self.lpassword.setObjectName("lpassword")
        self.lblpicture7 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture7.setGeometry(QtCore.QRect(10, 350, 151, 171))
        self.lblpicture7.setText("")
        self.lblpicture7.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture7.setScaledContents(True)
        self.lblpicture7.setObjectName("lblpicture7")
        self.lblpicture13 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture13.setGeometry(QtCore.QRect(10, 560, 151, 171))
        self.lblpicture13.setText("")
        self.lblpicture13.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture13.setScaledContents(True)
        self.lblpicture13.setObjectName("lblpicture13")
        self.lblid = QtWidgets.QLabel(self.centralwidget)
        self.lblid.setGeometry(QtCore.QRect(850, 100, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblid.setFont(font)
        self.lblid.setObjectName("lblid")
        self.bmyfeed = QtWidgets.QPushButton(self.centralwidget)
        self.bmyfeed.setGeometry(QtCore.QRect(20, 100, 75, 23))
        self.bmyfeed.setObjectName("bmyfeed")
        self.branking = QtWidgets.QPushButton(self.centralwidget)
        self.branking.setGeometry(QtCore.QRect(130, 100, 75, 23))
        self.branking.setObjectName("branking")
        self.txtausgabe = QtWidgets.QTextEdit(self.centralwidget)
        self.txtausgabe.setGeometry(QtCore.QRect(10, 990, 1151, 61))
        self.txtausgabe.setReadOnly(True)
        self.txtausgabe.setObjectName("txtausgabe")
        self.lblpicture19 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture19.setGeometry(QtCore.QRect(10, 780, 151, 171))
        self.lblpicture19.setText("")
        self.lblpicture19.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture19.setScaledContents(True)
        self.lblpicture19.setObjectName("lblpicture19")
        self.chboxdownload1 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload1.setGeometry(QtCore.QRect(40, 320, 70, 17))
        self.chboxdownload1.setObjectName("chboxdownload1")
        self.chboxdownload7 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload7.setGeometry(QtCore.QRect(40, 530, 70, 17))
        self.chboxdownload7.setObjectName("chboxdownload7")
        self.chboxdownload13 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload13.setGeometry(QtCore.QRect(40, 740, 70, 17))
        self.chboxdownload13.setObjectName("chboxdownload13")
        self.chboxdownload19 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload19.setGeometry(QtCore.QRect(40, 960, 70, 17))
        self.chboxdownload19.setObjectName("chboxdownload19")
        self.chboxdownload2 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload2.setGeometry(QtCore.QRect(240, 320, 70, 17))
        self.chboxdownload2.setObjectName("chboxdownload2")
        self.chboxdownload20 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload20.setGeometry(QtCore.QRect(240, 960, 70, 17))
        self.chboxdownload20.setObjectName("chboxdownload20")
        self.lblpicture14 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture14.setGeometry(QtCore.QRect(210, 560, 151, 171))
        self.lblpicture14.setText("")
        self.lblpicture14.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture14.setScaledContents(True)
        self.lblpicture14.setObjectName("lblpicture14")
        self.lblpicture20 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture20.setGeometry(QtCore.QRect(210, 780, 151, 171))
        self.lblpicture20.setText("")
        self.lblpicture20.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture20.setScaledContents(True)
        self.lblpicture20.setObjectName("lblpicture20")
        self.lblpicture8 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture8.setGeometry(QtCore.QRect(210, 350, 151, 171))
        self.lblpicture8.setText("")
        self.lblpicture8.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture8.setScaledContents(True)
        self.lblpicture8.setObjectName("lblpicture8")
        self.chboxdownload8 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload8.setGeometry(QtCore.QRect(240, 530, 70, 17))
        self.chboxdownload8.setObjectName("chboxdownload8")
        self.lblpicture2 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture2.setGeometry(QtCore.QRect(210, 140, 151, 171))
        self.lblpicture2.setText("")
        self.lblpicture2.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture2.setScaledContents(True)
        self.lblpicture2.setObjectName("lblpicture2")
        self.chboxdownload14 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload14.setGeometry(QtCore.QRect(240, 740, 70, 17))
        self.chboxdownload14.setObjectName("chboxdownload14")
        self.chboxdownload3 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload3.setGeometry(QtCore.QRect(440, 320, 70, 17))
        self.chboxdownload3.setObjectName("chboxdownload3")
        self.chboxdownload21 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload21.setGeometry(QtCore.QRect(440, 960, 70, 17))
        self.chboxdownload21.setObjectName("chboxdownload21")
        self.lblpicture15 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture15.setGeometry(QtCore.QRect(410, 560, 151, 171))
        self.lblpicture15.setText("")
        self.lblpicture15.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture15.setScaledContents(True)
        self.lblpicture15.setObjectName("lblpicture15")
        self.lblpicture21 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture21.setGeometry(QtCore.QRect(410, 780, 151, 171))
        self.lblpicture21.setText("")
        self.lblpicture21.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture21.setScaledContents(True)
        self.lblpicture21.setObjectName("lblpicture21")
        self.lblpicture9 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture9.setGeometry(QtCore.QRect(410, 350, 151, 171))
        self.lblpicture9.setText("")
        self.lblpicture9.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture9.setScaledContents(True)
        self.lblpicture9.setObjectName("lblpicture9")
        self.chboxdownload9 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload9.setGeometry(QtCore.QRect(440, 530, 70, 17))
        self.chboxdownload9.setObjectName("chboxdownload9")
        self.lblpicture3 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture3.setGeometry(QtCore.QRect(410, 140, 151, 171))
        self.lblpicture3.setText("")
        self.lblpicture3.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture3.setScaledContents(True)
        self.lblpicture3.setObjectName("lblpicture3")
        self.chboxdownload15 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload15.setGeometry(QtCore.QRect(440, 740, 70, 17))
        self.chboxdownload15.setObjectName("chboxdownload15")
        self.chboxdownload4 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload4.setGeometry(QtCore.QRect(640, 320, 70, 17))
        self.chboxdownload4.setObjectName("chboxdownload4")
        self.chboxdownload22 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload22.setGeometry(QtCore.QRect(640, 960, 70, 17))
        self.chboxdownload22.setObjectName("chboxdownload22")
        self.lblpicture16 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture16.setGeometry(QtCore.QRect(610, 560, 151, 171))
        self.lblpicture16.setText("")
        self.lblpicture16.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture16.setScaledContents(True)
        self.lblpicture16.setObjectName("lblpicture16")
        self.lblpicture22 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture22.setGeometry(QtCore.QRect(610, 780, 151, 171))
        self.lblpicture22.setText("")
        self.lblpicture22.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture22.setScaledContents(True)
        self.lblpicture22.setObjectName("lblpicture22")
        self.lblpicture10 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture10.setGeometry(QtCore.QRect(610, 350, 151, 171))
        self.lblpicture10.setText("")
        self.lblpicture10.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture10.setScaledContents(True)
        self.lblpicture10.setObjectName("lblpicture10")
        self.chboxdownload10 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload10.setGeometry(QtCore.QRect(640, 530, 70, 17))
        self.chboxdownload10.setObjectName("chboxdownload10")
        self.lblpicture4 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture4.setGeometry(QtCore.QRect(610, 140, 151, 171))
        self.lblpicture4.setText("")
        self.lblpicture4.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture4.setScaledContents(True)
        self.lblpicture4.setObjectName("lblpicture4")
        self.chboxdownload16 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload16.setGeometry(QtCore.QRect(640, 740, 70, 17))
        self.chboxdownload16.setObjectName("chboxdownload16")
        self.chboxdownload5 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload5.setGeometry(QtCore.QRect(840, 320, 70, 17))
        self.chboxdownload5.setObjectName("chboxdownload5")
        self.chboxdownload23 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload23.setGeometry(QtCore.QRect(840, 960, 70, 17))
        self.chboxdownload23.setObjectName("chboxdownload23")
        self.lblpicture17 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture17.setGeometry(QtCore.QRect(810, 560, 151, 171))
        self.lblpicture17.setText("")
        self.lblpicture17.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture17.setScaledContents(True)
        self.lblpicture17.setObjectName("lblpicture17")
        self.lblpicture23 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture23.setGeometry(QtCore.QRect(810, 780, 151, 171))
        self.lblpicture23.setText("")
        self.lblpicture23.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture23.setScaledContents(True)
        self.lblpicture23.setObjectName("lblpicture23")
        self.lblpicture11 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture11.setGeometry(QtCore.QRect(810, 350, 151, 171))
        self.lblpicture11.setText("")
        self.lblpicture11.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture11.setScaledContents(True)
        self.lblpicture11.setObjectName("lblpicture11")
        self.chboxdownload11 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload11.setGeometry(QtCore.QRect(840, 530, 70, 17))
        self.chboxdownload11.setObjectName("chboxdownload11")
        self.lblpicture5 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture5.setGeometry(QtCore.QRect(810, 140, 151, 171))
        self.lblpicture5.setText("")
        self.lblpicture5.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture5.setScaledContents(True)
        self.lblpicture5.setObjectName("lblpicture5")
        self.chboxdownload17 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload17.setGeometry(QtCore.QRect(840, 740, 70, 17))
        self.chboxdownload17.setObjectName("chboxdownload17")
        self.chboxdownload12 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload12.setGeometry(QtCore.QRect(1040, 530, 70, 17))
        self.chboxdownload12.setObjectName("chboxdownload12")
        self.chboxdownload18 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload18.setGeometry(QtCore.QRect(1040, 740, 70, 17))
        self.chboxdownload18.setObjectName("chboxdownload18")
        self.chboxdownload24 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload24.setGeometry(QtCore.QRect(1040, 960, 70, 17))
        self.chboxdownload24.setObjectName("chboxdownload24")
        self.lblpicture12 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture12.setGeometry(QtCore.QRect(1010, 350, 151, 171))
        self.lblpicture12.setText("")
        self.lblpicture12.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture12.setScaledContents(True)
        self.lblpicture12.setObjectName("lblpicture12")
        self.chboxdownload6 = QtWidgets.QCheckBox(self.centralwidget)
        self.chboxdownload6.setGeometry(QtCore.QRect(1040, 320, 70, 17))
        self.chboxdownload6.setObjectName("chboxdownload6")
        self.lblpicture6 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture6.setGeometry(QtCore.QRect(1010, 140, 151, 171))
        self.lblpicture6.setText("")
        self.lblpicture6.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture6.setScaledContents(True)
        self.lblpicture6.setObjectName("lblpicture6")
        self.lblpicture18 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture18.setGeometry(QtCore.QRect(1010, 560, 151, 171))
        self.lblpicture18.setText("")
        self.lblpicture18.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture18.setScaledContents(True)
        self.lblpicture18.setObjectName("lblpicture18")
        self.lblpicture24 = QtWidgets.QLabel(self.centralwidget)
        self.lblpicture24.setGeometry(QtCore.QRect(1010, 780, 151, 171))
        self.lblpicture24.setText("")
        self.lblpicture24.setPixmap(QtGui.QPixmap("../Users/bruce.lieber/Desktop/Testbilder/kek.png"))
        self.lblpicture24.setScaledContents(True)
        self.lblpicture24.setObjectName("lblpicture24")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1190, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pixiv Downloader"))
        self.bbrowse.setText(_translate("MainWindow", "Browse"))
        self.bdownload.setText(_translate("MainWindow", "Download"))
        self.blogin.setText(_translate("MainWindow", "Login"))
        self.lblusername.setText(_translate("MainWindow", "Username:"))
        self.lblpassword.setText(_translate("MainWindow", "Passwort:"))
        self.lblid.setText(_translate("MainWindow", "Pixiv ID:"))
        self.bmyfeed.setText(_translate("MainWindow", "My Feed"))
        self.branking.setText(_translate("MainWindow", "Ranking"))
        self.chboxdownload1.setText(_translate("MainWindow", "Download"))
        self.chboxdownload7.setText(_translate("MainWindow", "Download"))
        self.chboxdownload13.setText(_translate("MainWindow", "Download"))
        self.chboxdownload19.setText(_translate("MainWindow", "Download"))
        self.chboxdownload2.setText(_translate("MainWindow", "Download"))
        self.chboxdownload20.setText(_translate("MainWindow", "Download"))
        self.chboxdownload8.setText(_translate("MainWindow", "Download"))
        self.chboxdownload14.setText(_translate("MainWindow", "Download"))
        self.chboxdownload3.setText(_translate("MainWindow", "Download"))
        self.chboxdownload21.setText(_translate("MainWindow", "Download"))
        self.chboxdownload9.setText(_translate("MainWindow", "Download"))
        self.chboxdownload15.setText(_translate("MainWindow", "Download"))
        self.chboxdownload4.setText(_translate("MainWindow", "Download"))
        self.chboxdownload22.setText(_translate("MainWindow", "Download"))
        self.chboxdownload10.setText(_translate("MainWindow", "Download"))
        self.chboxdownload16.setText(_translate("MainWindow", "Download"))
        self.chboxdownload5.setText(_translate("MainWindow", "Download"))
        self.chboxdownload23.setText(_translate("MainWindow", "Download"))
        self.chboxdownload11.setText(_translate("MainWindow", "Download"))
        self.chboxdownload17.setText(_translate("MainWindow", "Download"))
        self.chboxdownload12.setText(_translate("MainWindow", "Download"))
        self.chboxdownload18.setText(_translate("MainWindow", "Download"))
        self.chboxdownload24.setText(_translate("MainWindow", "Download"))
        self.chboxdownload6.setText(_translate("MainWindow", "Download"))
